### PR TITLE
Epic 4 - Volodymyr Dashavskiy

### PR DESCRIPTION
**Pull request by DashavskiyVolodymyr**

### CODE REVIEW

**Review by taraaas — APPROVED** [review]
veri vell
volodya

**Comment by markotymofeiuk** [comment]
dababy-race 1

**Comment by l1ubek** [comment]
for boys
Men

**Review by markotymofeiuk — APPROVED** [review]
image

**Comment by l1ubek** [comment]
Aproove ( . Y  . )

14 Dogs Who Know What You Did Last Summer

**Review by l1ubek — COMMENTED** [review]
Shit-on!
Mongraal Shit-on Men's Premium T-shirt by Nadav Avni

**Comment by markotymofeiuk** [comment]
image

**Comment by taraaas** [comment]
gut
lalalalal

**Review by izagor — APPROVED** [review]

**Pull request merged**
