### PR TITLE
Epic 3 - Mariia Stepova

### PR DESCRIPTION
**Pull request by mariastepova**

### CODE REVIEW

**Comment by taraaas** [comment]
lgtm

**Review by taraaas — COMMENTED** [review]
LGTM

**Comment by SofiaPasichko** [comment]
Awesome!

**Review by SofiaPasichko — APPROVED** [review]

**Review by taraaas — APPROVED** [review]

**Review by PavloYaremchuk — COMMENTED** [review]
cool

**Review by rtriska — APPROVED** [review]
LGTM

**Pull request merged**
