### PR TITLE
Epic 6 - Taras Bortnyk

### PR DESCRIPTION
**Pull request by taraaas**

### CODE REVIEW

**Review by DashavskiyVolodymyr — COMMENTED** [review]
best epic6 report i've ever seen

**Comment by DashavskiyVolodymyr** [comment]
312aa13b46a666fd30bcde741ab9746d

**Review by markotymofeiuk — APPROVED** [review]
**LGTM**☑
travis-scott-travis-scott-apology 1

**Review by mariastepova — APPROVED** [review]
кул

**Review by dmytrosydor — COMMENTED** [review]
[
hello-travis 1
](url)

**Review by rtriska — APPROVED** [review]
LGTM

**Pull request merged**
