### PR TITLE
Epic 7 - Olena Novosad

### PR DESCRIPTION
**Pull request by olena-novosad**

### CODE REVIEW

**Comment by okohuch** [comment]
стоп

**Comment by izagor** [comment]
+ 12-19-2023

**Comment by olena-novosad** [comment]
#include <iostream>
#include <cmath>
#include <fstream>
#include <cstdlib>

using namespace std;

#define N 10

const char * name = "FILE_1.txt";

// Функція для створення матриці
double **create_matrix_double()
{
    double **matrix = new double *[N];
    for (int i = 0; i < N; ++i)
    {
        matrix[i] = new double[N];
    }

    for (int i = 0; i < N; ++i)
    {
        for (int j = 0; j < N; ++j)
        {
            matrix[i][j] = j != 0 ? atan(static_cast<double>(i) / static_cast<double>(j)) : 0.0;
        }
    }
    return matrix;
}

int **create_matrix_int()
{
    int **matrix = new int *[N];
    for (int i = 0; i < N; ++i)
    {
        matrix[i] = new int[N];
    }

    for (int i = 0; i < N; ++i)
    {
        for (int j = 0; j < N; ++j)
        {
            matrix[i][j] = j != 0 ? static_cast<int>(atan(static_cast<double>(i) / static_cast<double>(j))) : 0.0;
        }
    }
    return matrix;
}

void BubbleSortMatrix(double **arr, double n)
{
    for (int j = 0; j < N; ++j) // для стовпців
    {
        for (int k = 0; k < N; ++k) // для N бульбашок
        {
            for (int i = 0; i < N - 1; i++) {
                if (arr[i][j] > arr[i + 1][j])
                {
                    // Міняємо місцями
                    double temp = arr[i][j];
                    arr[i][j] = arr[i + 1][j];
                    arr[i + 1][j] = temp;
                }
            }
        }
    }
}


void BubbleSortMatrix(int **arr, int n)
{
    for (int i = 0; i < N; ++i) // для рядків
    {
        for (int k = 0; k < N; ++k) // для N бульбашок
        {
            for (int j = 0; j < N - 1; j++) {
                if (arr[i][j] < arr[i][j + 1])
                {
                    // Міняємо місцями
                    int temp = arr[i][j];
                    arr[i][j] = arr[i][j + 1];
                    arr[i][j + 1] = temp;
                }
            }
        }
    }
}

int Sums[N] = {0};

template <typename T>
void sumOfRandomElements(T **arr)
{
    for (int j = 0; j < N; ++j)
    {
        int k = 0;
        double sum = 0;
        while (k < 3)
        {
            int coord = rand() % N;
            int a = arr[j][coord];
            sum = sum + a;
            k++;
        }
        Sums[j] = static_cast<int>(sum);
    }
}

bool putDataIntoFile(int *arr)
{
    ofstream file("FILE_1.txt");
    bool success = false;
    if (!file)
    {
        return success;
    }
    for (int i = 0; i < N; i++)
    {
        file << arr[i] << "\t";
    }
    file.close();
    success = true;
    return success;
}

int multiplyElementsInFile()
{
    ifstream file("FILE_1.txt");

    if (!file.is_open())
    {
        cout << "Error: " << "FILE_1.txt" << endl;
        return 0;
    }
    int result = 1;
    int number;

    while (file >> number)
    {
        result *= number;
    }

    file.close();
    cout << "result: " << result << "\n";
    return result;
}

void deleteFile()
{
    if (remove("FILE_1.txt") == 0)
    {
        cout << "File is deleted successfully" << endl;
    }
    else
    {
        cout << "There is error in deleting this file" << endl;
    }
}

int main()
{
    const int number = 1012;
    
    if (number % 2 == 0)
    {
        double **matrix = create_matrix_double();
        
        BubbleSortMatrix(matrix, number);
        
        sumOfRandomElements<double>(matrix);
        
        putDataIntoFile(Sums);
        multiplyElementsInFile();
        deleteFile();
        
        for (int i = 0; i < N; ++i)
        {
            delete[] matrix[i];
        }
        delete[] matrix;
    }
    else
    {
        int **matrix = create_matrix_int();
        
        BubbleSortMatrix(matrix, number);
        
        sumOfRandomElements<int>(matrix);

        putDataIntoFile(Sums);
        multiplyElementsInFile();
        deleteFile();
        
        for (int i = 0; i < N; ++i)
        {
            delete[] matrix[i];
        }
        delete[] matrix;
    }

    return 0;
}

**Comment by olena-novosad** [comment]
`#include <iostream>
#include <cmath>
#include <fstream>
#include <cstdlib>

using namespace std;

#define N 10

const char * name = "FILE_1.txt";

// Функція для створення матриці
double **create_matrix_double()
{
    double **matrix = new double *[N];
    for (int i = 0; i < N; ++i)
    {
        matrix[i] = new double[N];
    }

    for (int i = 0; i < N; ++i)
    {
        for (int j = 0; j < N; ++j)
        {
            matrix[i][j] = j != 0 ? atan(static_cast<double>(i) / static_cast<double>(j)) : 0.0;
        }
    }
    return matrix;
}

int **create_matrix_int()
{
    int **matrix = new int *[N];
    for (int i = 0; i < N; ++i)
    {
        matrix[i] = new int[N];
    }

    for (int i = 0; i < N; ++i)
    {
        for (int j = 0; j < N; ++j)
        {
            matrix[i][j] = j != 0 ? static_cast<int>(atan(static_cast<double>(i) / static_cast<double>(j))) : 0.0;
        }
    }
    return matrix;
}

void BubbleSortMatrix(double **arr, double n)
{
    for (int j = 0; j < N; ++j) // для стовців
    {
        for (int k = 0; k < N; ++k) // для N бульбашок
        {
            for (int i = 0; i < N - 1; i++) {
                if (arr[i][j] > arr[i + 1][j])
                {
                    // Міняємо місцями
                    double temp = arr[i][j];
                    arr[i][j] = arr[i + 1][j];
                    arr[i + 1][j] = temp;
                }
            }
        }
    }
}


void BubbleSortMatrix(int **arr, int n)
{
    for (int i = 0; i < N; ++i) // для рядків
    {
        for (int k = 0; k < N; ++k) // для N бульбашок
        {
            for (int j = 0; j < N - 1; j++) {
                if (arr[i][j] < arr[i][j + 1])
                {
                    // Міняємо місцями
                    int temp = arr[i][j];
                    arr[i][j] = arr[i][j + 1];
                    arr[i][j + 1] = temp;
                }
            }
        }
    }
}

int Sums[N] = {0};

template <typename T>
void sumOfRandomElements(T **arr)
{
    for (int j = 0; j < N; ++j)
    {
        int k = 0;
        double sum = 0;
        while (k < 3)
        {
            int coord = rand() % N;
            int a = arr[j][coord];
            sum = sum + a;
            k++;
        }
        Sums[j] = static_cast<int>(sum);
    }
}

bool putDataIntoFile(int *arr)
{
    ofstream file("FILE_1.txt");
    bool success = false;
    if (!file)
    {
        return success;
    }
    for (int i = 0; i < N; i++)
    {
        file << arr[i] << "\t";
    }
    file.close();
    success = true;
    return success;
}

int multiplyElementsInFile()
{
    ifstream file("FILE_1.txt");

    if (!file.is_open())
    {
        cout << "Error: " << "FILE_1.txt" << endl;
        return 0;
    }
    int result = 1;
    int number;

    while (file >> number)
    {
        result *= number;
    }

    file.close();
    cout << "result: " << result << "\n";
    return result;
}

void deleteFile()
{
    if (remove("FILE_1.txt") == 0)
    {
        cout << "File is deleted successfully" << endl;
    }
    else
    {
        cout << "There is error in deleting this file" << endl;
    }
}

int main()
{
    const int number = 1012;
    
    if (number % 2 == 0)
    {
        double **matrix = create_matrix_double();
        
        BubbleSortMatrix(matrix, number);
        
        sumOfRandomElements<double>(matrix);
        
        putDataIntoFile(Sums);
        multiplyElementsInFile();
        deleteFile();
        
        for (int i = 0; i < N; ++i)
        {
            delete[] matrix[i];
        }
        delete[] matrix;
    }
    else
    {
        int **matrix = create_matrix_int();
        
        BubbleSortMatrix(matrix, number);
        
        sumOfRandomElements<int>(matrix);

        putDataIntoFile(Sums);
        multiplyElementsInFile();
        deleteFile();
        
        for (int i = 0; i < N; ++i)
        {
            delete[] matrix[i];
        }
        delete[] matrix;
    }

    return 0;
}`

**Pull request merged**
