### PR TITLE
Epic 6 - Marko Tymofeiuk

### PR DESCRIPTION
**Pull request by markotymofeiuk**

### CODE REVIEW

**Review by DashavskiyVolodymyr — COMMENTED** [review]
shashlyk
екфмі

**Review by l1ubek — COMMENTED** [review]
Awesome balls!
cristiano ronaldo navidad

**Review by dmytrosydor — COMMENTED** [review]
LGTM!!!
jax-jaxtart 1

**Comment by dmytrosydor** [comment]
mongraal-classic-fortnite 1

**Comment by maksymlirko** [comment]
👍

**Review by rtriska — APPROVED** [review]
LGTM

**Pull request merged**
