### PR TITLE
Epic 5 - Mariia Stepova

### PR DESCRIPTION
**Pull request by mariastepova**

### CODE REVIEW

**Review by taraaas — APPROVED** [review]
great job

**Comment by taraaas** [comment]
vol
lgtm

**Review by yurii-hr — APPROVED** [review]
WONDERFULLY!!!

**Review by PavloYaremchuk — APPROVED** [review]
Cool

**Review by fm2lpnu — APPROVED** [review]

**Review by fm2lpnu — APPROVED** [review]

**Pull request merged**
