### PR TITLE
Epic 6 - Alex Ivanov

### PR DESCRIPTION
**Pull request by Narkobaron15**

### CODE REVIEW

**Review by daniel-shliakhetko — APPROVED** [review]
молодець!

**Comment by olehio-p** [comment]
Looks very nice👍

**Review by olehio-p — APPROVED** [review]

**Comment by marko-kucheriavyi** [comment]
добре гарно!

**Review by AndrewVynnytskyi — APPROVED** [review]
You've done an excellent job! The code appears well-organized and straightforward.

**Review by izagor — APPROVED** [review]

**Pull request merged**
